const { z } = require("zod");
const svc = require("../services/tribunalService");
const prisma = require("../../prisma/client");

async function listAssignments(req, res, next) { try { const q=z.object({academicPeriodId:z.coerce.number().int().optional(), studentId:z.coerce.number().int().optional()}).parse(req.query||{}); const data=await svc.listAssignments(q); res.json(data);} catch(e){ if(e.name==='ZodError'){e.status=400;e.message=e.errors.map(x=>x.message).join(', ');} next(e);} }
async function createAssignment(req, res, next) { try { const b=z.object({id_user_student:z.coerce.number().int(), id_president:z.coerce.number().int(), id_secretary:z.coerce.number().int(), id_vocal:z.coerce.number().int(), academicPeriodId:z.coerce.number().int().optional(), careerId:z.coerce.number().int().optional()}).parse(req.body||{}); const data=await svc.createAssignment(b); try { const notifications=require('../services/notificationsService'); let studentLabel=String(b.id_user_student); try { const u=await prisma.usuarios.findUnique({ where:{ usuario_id:Number(b.id_user_student) }, select:{ nombre:true, apellido:true } }); const full=u?`${u.nombre||''} ${u.apellido||''}`.trim():''; if(full) studentLabel=full; } catch(_) {} const docentes=[b.id_president,b.id_secretary,b.id_vocal]; for(const id of docentes){ await notifications.create({ id_user:Number(id), type:'asignacion_tribunal', title:'Asignación de Tribunal', message:`Has sido asignado al tribunal del estudiante ${studentLabel}`, entity_type:'tribunal_assignment', entity_id:Number(data?.id||0) }); } await notifications.create({ id_user:Number(b.id_user_student), type:'asignacion_tribunal', title:'Tribunal asignado', message:'Se ha asignado tu tribunal de defensa', entity_type:'tribunal_assignment', entity_id:Number(data?.id||0) }); } catch(_){ /* no bloquear */ } res.status(201).json(data);} catch(e){ if(e.name==='ZodError'){e.status=400;e.message=e.errors.map(x=>x.message).join(', ');} next(e);} }
async function updateAssignment(req, res, next) { try { const p=z.object({id:z.coerce.number().int()}).parse({id:req.params.id}); const b=z.object({ id_president:z.coerce.number().int().optional(), id_secretary:z.coerce.number().int().optional(), id_vocal:z.coerce.number().int().optional(), defense_date:z.string().datetime().optional(), id_user_student:z.coerce.number().int().optional() }).parse({ ...req.body, id_user_student: req.body?.id_user_student }); const data=await svc.updateAssignment(p.id, { ...b, ...(b.defense_date?{ defense_date:new Date(b.defense_date)}:{}) }); try { const notifications=require('../services/notificationsService'); const changedDocentes=[b.id_president,b.id_secretary,b.id_vocal].filter(Boolean); for(const id of changedDocentes){ await notifications.create({ id_user:Number(id), type:'asignacion_actualizada', title:'Asignación de Tribunal actualizada', message:`Tu participación en un tribunal fue actualizada`, entity_type:'tribunal_assignment', entity_id:Number(p.id) }); } if(b.defense_date){ const ids=[b.id_user_student,b.id_president,b.id_secretary,b.id_vocal].filter(Boolean); for(const id of ids){ await notifications.create({ id_user:Number(id), type:'defensa_agendada', title:'Defensa agendada', message:`Fecha: ${new Date(b.defense_date).toLocaleString()}`, entity_type:'defense', entity_id:Number(p.id) }); } } } catch(_){ /* no bloquear */ } res.json(data);} catch(e){ if(e.name==='ZodError'){e.status=400;e.message=e.errors.map(x=>x.message).join(', ');} next(e);} }

async function scheduleDefense(req, res, next) { try { const b=z.object({ id_user_student:z.coerce.number().int(), scheduled_at:z.string().datetime(), location:z.string().optional(), academicPeriodId:z.coerce.number().int().optional(), id_president:z.coerce.number().int().optional(), id_secretary:z.coerce.number().int().optional(), id_vocal:z.coerce.number().int().optional() }).parse(req.body||{}); const data=await svc.scheduleDefense(b); try { const notifications=require('../services/notificationsService'); const ids=[b.id_user_student,b.id_president,b.id_secretary,b.id_vocal].filter(Boolean); for(const id of ids){ await notifications.create({ id_user:Number(id), type:'defensa_agendada', title:'Defensa agendada', message:`Fecha: ${new Date(b.scheduled_at).toLocaleString()}${b.location?` - ${b.location}`:''}`, entity_type:'defense', entity_id:Number(data?.id_defense||0) }); } } catch(_){ /* no bloquear */ } res.status(201).json(data);} catch(e){ if(e.name==='ZodError'){e.status=400;e.message=e.errors.map(x=>x.message).join(', ');} next(e);} }
async function listDefenses(req, res, next) { try { const q=z.object({academicPeriodId:z.coerce.number().int().optional(), studentId:z.coerce.number().int().optional()}).parse(req.query||{}); const data=await svc.listDefenses(q); res.json(data);} catch(e){ if(e.name==='ZodError'){e.status=400;e.message=e.errors.map(x=>x.message).join(', ');} next(e);} }
async function submitDefenseGrade(req, res, next) { try { const b=z.object({ id_defense:z.coerce.number().int(), score:z.coerce.number(), observation:z.string().optional(), id_user_student:z.coerce.number().int().optional() }).parse({ ...req.body, id_user_student: req.body?.id_user_student }); const id_judge=req.user?.sub; if(!id_judge){ const e=new Error('No autorizado'); e.status=401; throw e;} const data=await svc.submitDefenseGrade({ ...b, id_judge }); try { const notifications=require('../services/notificationsService'); if(b.id_user_student){ await notifications.create({ id_user:Number(b.id_user_student), type:'defensa_calificada', title:'Tu defensa fue calificada', message:`Calificación: ${b.score}`, entity_type:'defense_grade', entity_id:Number(data?.id||0) }); } } catch(_){ /* no bloquear */ } res.status(201).json(data);} catch(e){ if(e.name==='ZodError'){e.status=400;e.message=e.errors.map(x=>x.message).join(', ');} next(e);} }

module.exports = { listAssignments, createAssignment, updateAssignment, scheduleDefense, listDefenses, submitDefenseGrade };
